# port
server:
  port: 8013

# logging level
logging:
  level:
    root: debug
  config: classpath:log4j/log4j2.xml

#Spring cofnig
spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    #url: jdbc:log4jdbc:mysql://localhost:3306/PCONSOLEDB?serverTimezone=UTC
    #username: root
    #password: qwer1234
    url: jdbc:log4jdbc:mysql://develop-console-mysql.cqumm9p8ksgp.ap-northeast-2.rds.amazonaws.com:10025/PCONSOLEDB?serverTimezone=UTC
    username: PCONSOLE_OWN
    password: Pconsole_own~135

 