# port
server:
  port: 8080

# logging level
logging:
  level:
    root: debug
  config: classpath:log4j/log4j2.xml

#Spring cofnig
spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/web_study?serverTimezone=UTC
    username: root
    password: 1130
    hikari:
      pool-name: hikari-cp
      maximum-pool-size: 5
      connection-timeout: 5000
      connection-init-sql: SELECT 1
      validation-timeout: 5000
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000 
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher #swagger2 오류처리

  #error config
  error:
    whitelabel:
      enabled: false

  web:
    resources:
      add-mappings: false

  #message config
  messages:
    basename: i18n/message
    encoding: UTF-8

  #attach config
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB
      location: /Users/wm-id002599/web_study_files

#mybatis config
mybatis:
  configuration:
    multiple-result-sets-enabled: false
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: varchar
    default-fetch-size: 500
  type-aliases-package: com.board
  mapper-locations: classpath:mapper/*.xml

#httpConnPool config
httpConnPool: 
  maxTotal: 200
  defaultMaxPerRoute: 20
  maxPending: 50
  connectionRequestTimeout: 5000
  connectionTimeout: 3000
  socketTimeout: 3000

# swagger api-docs
springdoc:
  version: v1.0.0
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    tagsSorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: none
